intro completed
DilsherB/Portfolio pull request #1
Opened 2022-12-01 13:18 UTC by DilsherB

intro completed and merged in main

2022-12-01 14:08 UTC, andgarzonmal requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 Hi @DilsherB    ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 

### 💯  Highlights 💯
- Your gitHub flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️

### ♻️ Request changes ♻️

- [x] _Check the comments under the review._
___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-12-01 14:08 UTC, andgarzonmal commented on READme.md
> +This is my portfolio to show case my abilities in the field of software development.
- [ ]  Kindly add a professional readme file to your project, you can use the one from microverse [README template](https://github.com/microverseinc/readme-template)

2022-12-01 14:08 UTC, andgarzonmal commented on index.html
> +    </section>
Kindly stick to the Figma template as much as you can, please notice in the Figma template there are no buttons enabled, hover, pressed, or disabled.

## Figma design 
![image](https://user-images.githubusercontent.com/95243996/205071651-55d0de12-9dde-4855-9bfd-f98fefe5eeb2.png)

## Your design 

![image](https://user-images.githubusercontent.com/95243996/205071817-0db8e8f7-e189-4148-b05c-a3a5cc364438.png)

2022-12-01 14:08 UTC, andgarzonmal commented on index.html
> +        <div id="logo">Dilsher Balouch</div>
Kindly use an `a` tag on your logo, This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-12-01 14:08 UTC, andgarzonmal commented on index.html
> +        </div>
- [ ]  Kindly use a `ul` tag to wrap all of your social media icons, also remember as these icons will be linked to your social media use an `a` tag on each icon.

2022-12-01 15:32 UTC, DilsherB commented on index.html
> +        <div id="logo">Dilsher Balouch</div>
@andgarzonmal 
Thank you for your review and detailed explanation. I have done all these changes.

2022-12-01 15:37 UTC, DilsherB commented on index.html
> +        </div>
@andgarzonmal 
Thnaks a lot for detailed review/description. I have done all the changes mentioned by you. Please guide me whether I have to submit it again for review or not.

2022-12-01 17:20 UTC, brainconnect93 requested changes
### Hi @DilsherB  , 👋 

# STATUS: Changes Required :recycle:

Good job so far in implemented some of the changes the previous reviewer request for!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/M5SonVIGcOMAAAAj/rascal-almost-there.gif">


### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 17:20 UTC, brainconnect93 commented on index.html
> +    </nav>
- [x] Hi @DilsherB, well done to have worked on your project this far, I would kindly suggest you wrap your `<nav>` tag inside an `<header>` tag. Typically the `<header>` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

Hint on what am driving @: 👇 
```HTML
<header>
    <a href="#logo" id="logo">Dilsher Balouch</a>
    <nav>
       
    </nav>
</header>
```

2022-12-01 17:20 UTC, brainconnect93 commented on index.html
> +            <li></li><a href="#"><img src="images/hand.svg" alt=""></a></li>
- [x] I would suggest you check the closing tag of your `</li>` it's conflicting with each other. Kindly check it and rectify

2022-12-01 17:20 UTC, brainconnect93 commented on style.css
> +}
- [ ] I would suggest we stick to the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=t4fpDJvaCtvytWN0-0) as suggested by the previous reviewer. 

- This is the Figma template 👇 

![real](https://user-images.githubusercontent.com/78634841/205116531-b8cd30d4-ffda-484e-a6f6-47e34f621063.png)

- And this is what you have in your project 👇 

![temp1](https://user-images.githubusercontent.com/78634841/205116667-37fcff8a-881d-44e1-bc0b-234d54909fad.png)

- Kindly follow the highlighted arrows to see what changes I am requesting for

1.  Kindly make the content of the project align with the title as seen in the template, also there should be some `padding left` in order for them to have some spaces away from the wall
2. Kindly check your social media icons too and fix their alignment, also remove the dot sign showing around the icons. You can simply do that by giving the list some styling value of `<list-style-type: none;>`

2022-12-01 17:59 UTC, DilsherB commented on style.css
> +}
@brainconnect93 
Thanks for your feedback.
I have done all but unable to align the social media icons. **_Can you help me in this?_**

2022-12-02 04:45 UTC, DilsherB commented
Social media alignment is done

2022-12-02 05:08 UTC, mavericks-db approved these changes
Hi **@DilsherB** 😃 , 

# Approved 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif)

## Highlights

- Required changes implemented
- Have use the right GitHub flow ✅
- Meaningful title and summary for PR ✅
- Descriptive commit messages ✅
- Professional README.md file ✅
- Linter checks passed ✅

## Optional suggestions

- **[OPTIONAL]**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Code review by **Mavericks De Leon Balitaan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 15:01 UTC, merged