Contact form added.
DilsherB/Portfolio pull request #3
Opened 2022-12-06 13:46 UTC by DilsherB

Contact form added.

2022-12-06 14:10 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @DilsherB , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a project, that has non exhaustive README file and a bad PR decription, kindly update your README file with all the necessary fields from the template you used and also please consider writing a meaning and descriptive PR description with title. The submit again for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-06 14:51 UTC, roshan-bajgain reviewed
Hi @DilsherB, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been done alone but this is a pair-programming project and we will check the commit history. Please implement the project with your partner.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏a

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-06 17:21 UTC, TadesseDev requested changes
### Hi @DilsherB 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![EquatorialVictoriousBlackpanther-size_restricted](https://user-images.githubusercontent.com/69077061/204090500-5512fd84-cfd9-4aee-9d5d-8ee90740a92d.gif)

## Highlights
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 17:21 UTC, Tadesse-Alemayehu commented on index.html
> +    </section>
- [ ] Good job adding the `action` and `method` attributes, But currently user cannot submit to `formspree.io`. As you can see down from the browser dev tools your form spare is not found. Please make sure the user can successfully submit a form to  `formspree.io`, Without this feature the form will be useless.
![Capture](https://user-images.githubusercontent.com/69077061/205976759-425d1179-f0fa-49dd-8f3a-18bdbb5ee353.PNG)

2022-12-06 17:21 UTC, Tadesse-Alemayehu commented on style.css
> +}
### Good job on the CSS @DilsherB, Some suggestion will be 
- [ ] Please use `flexbox` to align elements here, This is among the main requirements. 
- [ ] Please make sure `your form content` is aligned center and the button is aligned to the right as displayed in the Figma design. 
- [ ] Please apply the appropriate background images for the form. This is to make sure you are capable of parsing a design into a webpage. 
> Remember: you are expected to stick to the design templates in Figma as much as possible, this includes the font, colors, images, and spacing (margin/padding).

### Figma design
![figma](https://user-images.githubusercontent.com/69077061/205978912-931a6ae5-c8f3-4724-9e70-f36560a1cdf8.PNG)

### Your design
![your](https://user-images.githubusercontent.com/69077061/205978920-042149df-d999-459a-a64f-1357144a4eb7.PNG)

2022-12-07 06:10 UTC, DilsherB commented on style.css
> +}
@Tadesse-Alemayehu

2022-12-07 06:11 UTC, DilsherB commented on style.css
> +}
thanks for your kind review all the points raised by you are resolved

2022-12-07 06:47 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @DilsherB 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 07:01 UTC, merged